---
hot_accounts:
  - "HOT_ACCOUNT|1"
  - "HOT_ACCOUNT|2"
  - "HOT_ACCOUNT|3"
  - "HOT_ACCOUNT|4"
  - "HOT_ACCOUNT|5"
  - "HOT_ACCOUNT|6"
  - "HOT_ACCOUNT|7"
  - "HOT_ACCOUNT|8"
  - "HOT_ACCOUNT|9"
  - "HOT_ACCOUNT|10"
